=== norranlol/TestXMLProject/config/xsd/airport.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://www.airport.ru"
            elementFormDefault="qualified"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.airport.ru"
            xmlns:tns="http://www.airport.ru">
<xs:element name="flights">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="flight" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="id" type="xs:integer"/>
                        <xs:element name="timeOfDeparture" type="xs:dateTime"/>
                        <xs:element name="timeOfArrival" type="xs:dateTime"/>
                        <xs:element name="pilot" minOccurs="1" maxOccurs="4" type="pilot"/>
                        <xs:element name="plane" type="fly"/>
                        <xs:element name="route" type="route"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="ticket" minOccurs="0" maxOccurs="500" type="ticket"/>
        </xs:sequence>
    </xs:complexType>
    <xs:key name="FlightNumberKey">
        <xs:selector xpath=".//flight"/>
        <xs:field xpath="@id"/>
    </xs:key>
    <xs:unique name="UniqueFlightNumber">
        <xs:selector xpath=".//flight"/>
        <xs:field xpath="@id"/>
    </xs:unique>
    <xs:keyref name="FlightNumberKeyRef" refer="FlightNumberKey">
        <xs:selector xpath=".//ticket"/>
        <xs:field xpath="@flightId"/>
    </xs:keyref>
</xs:element>
    
<xs:complexType name="pilotBase">
    <xs:sequence>
        <xs:element name="id" type="xs:integer"/>
        <xs:element name="surname" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="patronymic" type="xs:string"/>
        <xs:element name="category" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="point">
    <xs:sequence>
        <xs:element name="id" type="xs:integer"/>
        <xs:element name="country" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="fly" abstract="true"/>

<xs:complexType name="plane">
    <xs:complexContent>
        <xs:extension base="fly">
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="model" type="enumOfPlainModels"/>
                <xs:element name="year" type="yearInteger"/>
                <xs:element name="countOfRows" type="xs:integer"/>
                <xs:element name="placesInRow" type="xs:integer"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:simpleType name="yearInteger">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="1980"/>
        <xs:maxInclusive value="2015"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="titleString">
    <xs:restriction base="xs:string">
        <xs:minLength value="5"/>
        <xs:maxLength value="40"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="enumOfPlainModels">
    <xs:restriction base="xs:string">
        <xs:enumeration value="A310"/>
        <xs:enumeration value="A311"/>
        <xs:enumeration value="A312"/>
        <xs:enumeration value="A320"/>
        <xs:enumeration value="A329"/>
        <xs:enumeration value="A330"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="routeBase">
    <xs:sequence>
        <xs:element name="id" type="xs:integer"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="pointOfDeparture" type="point"/>
        <xs:element name="pointOfArrival" type="point"/>
        <xs:element name="cipher" type="xs:string"/>
        <xs:element name="distance" type="xs:integer"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="client">
    <xs:sequence>
        <xs:element name="id" type="xs:integer"/>
        <xs:element name="surname" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="patronymic" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="anonymousClient">
    <xs:all>
        <xs:element name="companyName" type="encodedString" />
        <xs:element name="employeerId" type="employeerIdInteger"/>
    </xs:all>
</xs:complexType>

<!--Ограничение сложного типа-->
<xs:complexType name="route">
    <xs:complexContent>
        <xs:restriction base="routeBase">
            <xs:sequence>
                <xs:element name="id" type="xs:integer"/>
                <xs:element name="title" type="titleString"/>
                <xs:element name="pointOfDeparture" type="point"/>
                <xs:element name="pointOfArrival" type="point"/>
                <xs:element name="cipher" type="xs:string" fixed="D353512GSDGGHFHFN34"/>
                <xs:element name="distance" type="xs:integer"/>
            </xs:sequence>
        </xs:restriction>
    </xs:complexContent>
</xs:complexType>

<!--Ограничение простого типа-->
<xs:simpleType name="employeerIdInteger">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="10000"/>
    </xs:restriction>
</xs:simpleType>

<!--Расширение сложного типа-->
<xs:complexType name="pilot">
    <xs:complexContent>
        <xs:extension base="pilotBase">
            <xs:sequence>
                <xs:element name="certificateNumber" type="xs:string"/>
                <xs:element name="phoneNumber" type="xs:string"/>
                <xs:element name="eMail" type="xs:string"/>
                <xs:element name="address" type="xs:string"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<!--Расширение простого типа-->
<xs:complexType name="encodedString">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="officialName" type="xs:string"/>
            <xs:attribute name="englishName" type="xs:string"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="ticket">
    <xs:sequence>
        <xs:element name="id" type="xs:integer"/>
        <xs:element name="row" type="xs:integer"/>
        <xs:element name="place" type="xs:integer"/>
        <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="price" type="xs:integer"/>
        <xs:choice>
            <xs:element name="client" minOccurs="0" maxOccurs="1" type="client"/>
            <xs:element name="anonimousClient" minOccurs="0" maxOccurs="1" type="anonymousClient"/>
        </xs:choice>
    </xs:sequence>
    <xs:attribute name="flightId" type="xs:integer"/>
</xs:complexType>

</xs:schema>

=== norranlol/TestXMLProject/data/data2.xml
<?xml version="1.0" encoding="utf-8"?>
<flights xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://www.airport.ru"
              xmlns:tns="http://www.airport.ru"
              xsi:schemaLocation="http://www.airport.ru ../config/xsd/airport.xsd">
    <flight>
        <id>3535</id>
        <timeOfDeparture>2014-09-15T21:30:00</timeOfDeparture>
        <timeOfArrival>2014-04-16T05:00:00</timeOfArrival>
        <pilot>
            <id>1</id>
            <surname>Пупкин</surname>
            <name>Петр</name>
            <patronymic>Тимофеевич</patronymic>
            <category>1</category>
            <certificateNumber>F3421</certificateNumber>
            <phoneNumber>89034534412</phoneNumber>
            <eMail>pupkin.petr@mail.ru</eMail>
            <address>г.Владимир ул.Петрозаводская д.14 кв.34</address>
        </pilot>
        <pilot>
            <id>2</id>
            <surname>Губов</surname>
            <name>Дмитрий</name>
            <patronymic>Епархович</patronymic>
            <category>2</category>
            <certificateNumber>A3431</certificateNumber>
            <phoneNumber>89243535542</phoneNumber>
            <eMail>gubov.dmitry@mail.ru</eMail>
            <address>г.Владимир ул.Грибоедова д.24 кв.55</address>
        </pilot>
        <plane xsi:type="plane">
            <id>1</id>
            <model>A310</model>
            <year>1995</year>
            <countOfRows>10</countOfRows>
            <placesInRow>9</placesInRow>
        </plane>
        <route>
            <id>1</id>
            <title>Москва - Барселона</title>
            <pointOfDeparture>
                <id>1</id>
                <country>Россия</country>
                <city>Москва</city>
            </pointOfDeparture>
            <pointOfArrival>
                <id>2</id>
                <country>Испания</country>
                <city>Барселона</city>
            </pointOfArrival>
            <cipher>D353512GSDGGHFHFN34</cipher>
            <distance>3200</distance>
        </route>
    </flight>
    <flight>
        <id>3535</id>
        <timeOfDeparture>2014-05-12T18:00:00</timeOfDeparture>
        <timeOfArrival>2014-05-12T22:00:00</timeOfArrival>
        <pilot>
            <id>4</id>
            <surname>Грибоедов</surname>
            <name>Василий</name>
            <patronymic>Васильевич</patronymic>
            <category>1</category>
            <certificateNumber>K4531</certificateNumber>
            <phoneNumber>8932245322</phoneNumber>
            <eMail>griboed@mail.ru</eMail>
            <address>г.Владимир ул.Безыменского д.14 кв.33</address>
        </pilot>
        <plane xsi:type="plane">
            <id>4</id>
            <model>A329</model>
            <year>1993</year>
            <countOfRows>4</countOfRows>
            <placesInRow>5</placesInRow>
        </plane>
        <route>
            <id>2</id>
            <title>Лондон - Берлин</title>
            <pointOfDeparture>
                <id>6</id>
                <country>Англия</country>
                <city>Лондон</city>
            </pointOfDeparture>
            <pointOfArrival>
                <id>7</id>
                <country>Германия</country>
                <city>Берлин</city>
            </pointOfArrival>
            <cipher>D353512GSDGGHFHFN34</cipher>
            <distance>1200</distance>
        </route>
    </flight>
    <ticket flightId="3535">
        <id>1</id>
        <row>3</row>
        <place>4</place>
        <status>З</status>
        <price>8800</price>
        <client>
            <id>1</id>
            <surname>Петров</surname>
            <name>Григорий</name>
            <patronymic>Васильевич</patronymic>
        </client>
    </ticket>
    <ticket flightId="3534">
        <id>2</id>
        <row>5</row>
        <place>6</place>
        <price>870</price>
        <client>
            <id>2</id>
            <surname>Андреев</surname>
            <name>Михаил</name>
            <patronymic>Андреевич</patronymic>
        </client>
    </ticket>
    <ticket flightId="3534">
        <id>3</id>
        <row>6</row>
        <place>5</place>
        <status>З</status>
        <price>10000</price>
        <anonimousClient>
            <companyName>ФСБ</companyName>
            <employeerId>9999</employeerId>
        </anonimousClient>
    </ticket>
</flights>
